SELECT * FROM shopping_data;
ALTER TABLE shopping_data
RENAME COLUMN `purchase_amount()` TO purchase_amount;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue 
from shopping_data
group by gender


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from shopping_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from shopping_data);

# Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) as avg_rating 
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5


#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from shopping_data
where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM shopping_data
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM shopping_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


#Q.7) What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

#Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;



